### ISSUE TITLE
Missing completion on css

### ISSUE THREAD

**Issue by MartinHornung** [atom/autocomplete-css#34]
Hi,

I'm brand new to Atom - just installed it today.

I tried to do autocomplete for background-color: transparent, but nothing shows up.

Any deadline for getting the last things to work?
 I would really like to move from Sublime and to Atom - but this bugs me :)

Best regards, 
Martin

**Comment by c0nsu1tant** [comment]
Hi.

I have same problem when I write tags in one line.
So, if I write:

``` css
.tag { font-width: bold }
```

Atom helps me with "font-width" but not with "bold".
If I write:

``` css
.tag { 
   font-width: bold 
}
```

Atom helps me with both of property and value.

I think this is not a feature :) and shosuld be corrected.

Thanks
