### ISSUE TITLE
Remove parenthesis from autocompletion of values

### ISSUE THREAD

**Issue by dcalhoun** [atom/autocomplete-css#40]
Currently, autocomplete includes parenthesis (and closing semicolons) to values that require parenthesis (e.g. – `translate()`). In theory this sounds nice, but in practice it just requires a user to move their cursor backwards into the parenthesis.

Autocompleting the "translate" value is an example:

``` css
.some-selector {
  transform: translate();[CURSOR]
}
```

Given that placing the cursor within the parenthesis is not within the scope of autocomplete and [should be handled by a snippet](https://github.com/atom/autocomplete-css/issues/39#issuecomment-167929678), I propose it's better to not autocomplete values like this with parenthesis and semicolons.

``` css
.some-selector {
  transform: translate[CURSOR]
}
```

There are plenty of values that fall into this, `translate` is just one example.
